// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Namespaces, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

const localeTranslationLoaders = {
	cs: () => import('./cs'),
	en: () => import('./en'),
	pl: () => import('./pl'),
	sk: () => import('./sk'),
}

const localeNamespaceLoaders = {
	cs: {
		canvas: () => import('./cs/canvas'),
		common: () => import('./cs/common'),
		components: () => import('./cs/components'),
		configs: () => import('./cs/configs'),
		editor: () => import('./cs/editor'),
		'export': () => import('./cs/export'),
		mobile: () => import('./cs/mobile'),
		screen: () => import('./cs/screen')
	},
	en: {
		canvas: () => import('./en/canvas'),
		common: () => import('./en/common'),
		components: () => import('./en/components'),
		configs: () => import('./en/configs'),
		editor: () => import('./en/editor'),
		'export': () => import('./en/export'),
		mobile: () => import('./en/mobile'),
		screen: () => import('./en/screen')
	},
	pl: {
		canvas: () => import('./pl/canvas'),
		common: () => import('./pl/common'),
		components: () => import('./pl/components'),
		configs: () => import('./pl/configs'),
		editor: () => import('./pl/editor'),
		'export': () => import('./pl/export'),
		mobile: () => import('./pl/mobile'),
		screen: () => import('./pl/screen')
	},
	sk: {
		canvas: () => import('./sk/canvas'),
		common: () => import('./sk/common'),
		components: () => import('./sk/components'),
		configs: () => import('./sk/configs'),
		editor: () => import('./sk/editor'),
		'export': () => import('./sk/export'),
		mobile: () => import('./sk/mobile'),
		screen: () => import('./sk/screen')
	}
}

const updateDictionary = (locale: Locales, dictionary: Partial<Translations>): Translations =>
	loadedLocales[locale] = { ...loadedLocales[locale], ...dictionary }

export const importLocaleAsync = async (locale: Locales): Promise<Translations> =>
	(await localeTranslationLoaders[locale]()).default as unknown as Translations

export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
	updateDictionary(locale, await importLocaleAsync(locale))
	loadFormatters(locale)
}

export const loadAllLocalesAsync = (): Promise<void[]> => Promise.all(locales.map(loadLocaleAsync))

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))

export const importNamespaceAsync = async<Namespace extends Namespaces>(locale: Locales, namespace: Namespace) =>
	(await localeNamespaceLoaders[locale][namespace]()).default as unknown as Translations[Namespace]

export const loadNamespaceAsync = async <Namespace extends Namespaces>(locale: Locales, namespace: Namespace): Promise<void> =>
	void updateDictionary(locale, { [namespace]: await importNamespaceAsync(locale, namespace )})
