// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import cs from './cs'
import en from './en'
import pl from './pl'
import sk from './sk'

import cs_canvas from './cs/canvas'
import cs_common from './cs/common'
import cs_components from './cs/components'
import cs_configs from './cs/configs'
import cs_editor from './cs/editor'
import cs_export from './cs/export'
import cs_mobile from './cs/mobile'
import cs_screen from './cs/screen'
import en_canvas from './en/canvas'
import en_common from './en/common'
import en_components from './en/components'
import en_configs from './en/configs'
import en_editor from './en/editor'
import en_export from './en/export'
import en_mobile from './en/mobile'
import en_screen from './en/screen'
import pl_canvas from './pl/canvas'
import pl_common from './pl/common'
import pl_components from './pl/components'
import pl_configs from './pl/configs'
import pl_editor from './pl/editor'
import pl_export from './pl/export'
import pl_mobile from './pl/mobile'
import pl_screen from './pl/screen'
import sk_canvas from './sk/canvas'
import sk_common from './sk/common'
import sk_components from './sk/components'
import sk_configs from './sk/configs'
import sk_editor from './sk/editor'
import sk_export from './sk/export'
import sk_mobile from './sk/mobile'
import sk_screen from './sk/screen'

const localeTranslations = {
	cs: {
		...cs,
		canvas: cs_canvas,
		common: cs_common,
		components: cs_components,
		configs: cs_configs,
		editor: cs_editor,
		'export': cs_export,
		mobile: cs_mobile,
		screen: cs_screen
	},
	en: {
		...en,
		canvas: en_canvas,
		common: en_common,
		components: en_components,
		configs: en_configs,
		editor: en_editor,
		'export': en_export,
		mobile: en_mobile,
		screen: en_screen
	},
	pl: {
		...pl,
		canvas: pl_canvas,
		common: pl_common,
		components: pl_components,
		configs: pl_configs,
		editor: pl_editor,
		'export': pl_export,
		mobile: pl_mobile,
		screen: pl_screen
	},
	sk: {
		...sk,
		canvas: sk_canvas,
		common: sk_common,
		components: sk_components,
		configs: sk_configs,
		editor: sk_editor,
		'export': sk_export,
		mobile: sk_mobile,
		screen: sk_screen
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
