import { getLL } from '@/i18n/getLL'

const f = getLL().configs.fonts

export const FONTS = [
  { label: f.defaultFont(), value: '' },
  { label: f.sourceHanSans(), value: 'SourceHanSans' },
  { label: f.sourceHanSerif(), value: 'SourceHanSerif' },
  { label: f.wenDingPLKaiTi(), value: 'WenDingPLKaiTi' },
  { label: f.wenDingPLSongTi(), value: 'WenDingPLSongTi' },
  { label: f.zhuqueFangSong(), value: 'ZhuqueFangSong' },
  { label: f.lxgwwenKai(), value: 'LXGWWenKai' },
  { label: f.alibabaPuHuiTi(), value: 'AlibabaPuHuiTi' },
  { label: f.miSans(), value: 'MiSans' },
  { label: f.deYiHei(), value: 'DeYiHei' },
  { label: f.cangerXiaowanzi(), value: 'CangerXiaowanzi' },
  { label: f.yousheTitleBlack(), value: 'YousheTitleBlack' },
  { label: f.fengguangMingrui(), value: 'FengguangMingrui' },
  { label: f.shetuModernSquare(), value: 'ShetuModernSquare' },
  { label: f.zcoolHappy(), value: 'ZcoolHappy' },
  { label: f.zizhiQuXiMai(), value: 'ZizhiQuXiMai' },
  { label: f.sucaiJishiKangkang(), value: 'SucaiJishiKangkang' },
  { label: f.sucaiJishiCoolSquare(), value: 'SucaiJishiCoolSquare' },
  { label: f.tuniuRounded(), value: 'TuniuRounded' },
  { label: f.ruiziZhenyan(), value: 'RuiziZhenyan' },
  { label: f.sourceSerif4(), value: 'SourceSerif4' },
  { label: f.jetBrainsMono(), value: 'JetBrainsMono' },
  { label: f.literata(), value: 'Literata' },
  { label: f.inter(), value: 'Inter' },
  { label: f.roboto(), value: 'Roboto' },
  { label: f.openSans(), value: 'OpenSans' },
  { label: f.montserrat(), value: 'Montserrat' },
  { label: f.sourceSansPro(), value: 'SourceSansPro' },
  { label: f.merriweather(), value: 'Merriweather' },
]
