export const FONTS = [
  { label: 'Default Font', value: '' },
  { label: 'Source Han Sans', value: 'SourceHanSans' },
  { label: 'Source Han Serif', value: 'SourceHanSerif' },
  { label: 'FangZheng HeiTi', value: 'FangZhengHeiTi' },
  { label: 'FangZheng KaiTi', value: 'FangZhengKaiTi' },
  { label: 'FangZheng ShuSong', value: 'FangZhengShuSong' },
  { label: 'FangZheng FangSong', value: 'FangZhengFangSong' },
  { label: 'Alibaba PuHuiTi', value: 'AlibabaPuHuiTi' },
  { label: 'Zhuque FangSong', value: 'ZhuqueFangSong' },
  { label: 'LXGW WenKai', value: 'LXGWWenKai' },
  { label: 'WenDing PL KaiTi', value: 'WenDingPLKaiTi' },
  { label: 'Smiley Sans', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Tsanger Xiaowanzi', value: 'CangerXiaowanzi' },
  { label: 'Youshe Title Black', value: 'YousheTitleBlack' },
  { label: 'FG Sharp', value: 'FengguangMingrui' },
  { label: 'Shetu Modern Square', value: 'ShetuModernSquare' },
  { label: 'ZCOOL Happy', value: 'ZcoolHappy' },
  { label: 'ZCOOL XiMai', value: 'ZizhiQuXiMai' },
  { label: 'Sucai Jishi Kangkang', value: 'SucaiJishiKangkang' },
  { label: 'Sucai Jishi Cool Square', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuniu Rounded', value: 'TuniuRounded' },
  { label: 'RayLi Zhenyan', value: 'RuiziZhenyan' },
]